export const INIT_PLACEMENT_TEST = "INIT_PLACEMENT_TEST";
export const REMOVE_PLACEMENT_TEST = "REMOVE_PLACEMENT_TEST";
export const TOGGLE_QUESTION = "TOGGLE_QUESTION";
export const SAVE_ANSWER = "SAVE_ANSWER";
export const UPDATE_STATE = "UPDATE_STATE";
